version: '3'
services:
  # MySQL database container
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Gin web application container
  gin-rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gin-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_DB: mydb

volumes:
  mysql-data:
